### ISSUE TITLE
最新的编译不成功

### ISSUE THREAD

**Issue by ilxp** [JMVoid/ClashWRT#1]
感谢大佬的clashwrt，但我编译不成功： 
make[3] -C package/diy/luci-app-clashwrt compile
    ERROR: package/diy/luci-app-clashwrt failed to build. 相关依赖已经做全。openwrt 1806和1907均不能编译成功

日志：
make[3]: Entering directory '/workdir/openwrt/package/diy/luci-app-clashwrt'
touch /workdir/openwrt/build_dir/target-x86_64_musl/luci-app-clashwrt/.prepared_9c7e9c6121ede431caa238789472a7f6_6664517399ebbbc92a37c5bb081b5c53_check
cp -fpR /workdir/openwrt/package/diy/luci-app-clashwrt/root /workdir/openwrt/build_dir/target-x86_64_musl/luci-app-clashwrt
cp -fpR /workdir/openwrt/package/diy/luci-app-clashwrt/luasrc /workdir/openwrt/build_dir/target-x86_64_musl/luci-app-clashwrt
po2lmo /workdir/openwrt/package/diy/luci-app-clashwrt/po/zh-cn/clashwrt.zh-cn.po /workdir/openwrt/build_dir/target-x86_64_musl/luci-app-clashwrt/clashwrt.zh-cn.lmo;
chmod 0755 /workdir/openwrt/build_dir/target-x86_64_musl/luci-app-clashwrt/root/etc/init.d/clashwrt
chmod -R 0755 /workdir/openwrt/build_dir/target-x86_64_musl/luci-app-clashwrt/root/usr/share/clashwrt/
mkdir -p /workdir/openwrt/build_dir/target-x86_64_musl/luci-app-clashwrt/root/etc/clashwrt/config
mkdir -p /workdir/openwrt/build_dir/target-x86_64_musl/luci-app-clashwrt/root/etc/clashwrt/backup
mkdir -p /workdir/openwrt/build_dir/target-x86_64_musl/luci-app-clashwrt/root/etc/clashwrt/core
mkdir -p /workdir/openwrt/build_dir/target-x86_64_musl/luci-app-clashwrt/root/usr/share/clashwrt/backup
cp -f "/workdir/openwrt/build_dir/target-x86_64_musl/luci-app-clashwrt/root/etc/config/clashwrt" "/workdir/openwrt/build_dir/target-x86_64_musl/luci-app-clashwrt/root/usr/share/clashwrt/backup/clashwrt" >/dev/null 2>&1
cp -f "/workdir/openwrt/build_dir/target-x86_64_musl/luci-app-clashwrt/root/etc/clashwrt/custom/clashwrt_custom_fake_filter.list" "/workdir/openwrt/build_dir/target-x86_64_musl/luci-app-clashwrt/root/usr/share/clashwrt/backup/clashwrt_custom_fake_filter.list" >/dev/null 2>&1
make[3]: *** [Makefile:111: /workdir/openwrt/build_dir/target-x86_64_musl/luci-app-clashwrt/.prepared_9c7e9c6121ede431caa238789472a7f6_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/workdir/openwrt/package/diy/luci-app-clashwrt'
time: package/diy/luci-app-clashwrt/compile#0.23#0.10#0.32
    ERROR: package/diy/luci-app-clashwrt failed to build.
make[2]: *** [package/Makefile:116: package/diy/luci-app-clashwrt/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2

**Comment by JMVoid** [comment]
对不起了。该项目完成度只有50%不到。我暂时会转成闭源。完成后再重新开源..
